[BUGFIX] type error in 'max' with TYPO3 13.2.0
With auto-creation of TCA type 'input' fields introduced in TYPO3
13.2.0, the `max` property is now required to be of type int if present.
Otherwise, a type error is thrown:

    TypeError: Doctrine\DBAL\Schema\Column::setLength():
        Argument #1 ($length) must be of type ?int, string given,
        called in vendor/doctrine/dbal/src/Schema/Column.php on line 65
    vendor/doctrine/dbal/src/Schema/Column.php:78
    vendor/doctrine/dbal/src/Schema/Column.php:65
    vendor/doctrine/dbal/src/Schema/Column.php:52
    vendor/doctrine/dbal/src/Schema/Table.php:261
    vendor/typo3/cms-core/Classes/Database/Schema/DefaultTcaSchema.php:784
    vendor/typo3/cms-core/Classes/Database/Schema/DefaultTcaSchema.php:70
    vendor/typo3/cms-core/Classes/Database/Schema/SchemaMigrator.php:433
    vendor/typo3/cms-core/Classes/Database/Schema/SchemaMigrator.php:218
    vendor/typo3/cms-core/Classes/Database/Schema/SchemaMigrator.php:149
    vendor/typo3/testing-framework/Classes/Core/Testbase.php:896
    vendor/typo3/testing-framework/Classes/Core/Functional/FunctionalTestCase.php:382

Relates to clickstorm/cs_seo#325.

See: https://github.com/TYPO3/typo3/commit/ee2d3c6db3e193c2ff8c22e6f20d5519c51ae4d2
See: https://github.com/TYPO3/typo3/commit/37a08eaaa3016ec3a65ba45b370733da8ef07762